### ISSUE TITLE
Mesos framework authentication

### ISSUE THREAD

**Issue by adam-mesos** [mesos/chronos#293]
See the [Mesos Credential protobuf message definition](https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L689)

**Sub-tasks:**

- [x] Accept a framework principal
- [x] Accept a path to a secret (more secure than secret on cmdline)
- [x] Pass principal and secret to the `SchedulerDriver` as a `Credential`
- [x] Set the principal value in the `FrameworkInfo` message during registration.

_Notes:_ Secret should not be necessarily required, for maximum flexibility in auth modes.

Also see the related issue/PRs from Marathon:
https://github.com/mesosphere/marathon/issues/638
https://github.com/mesosphere/marathon/pull/710
https://github.com/mesosphere/marathon/pull/723

**Comment by swartzrock** [comment]
There is an alternate MesosSchedulerDriver constructor that takes the mesos credentials. However, I find that using this causes problems with the JobScheduler's LeaderLatch.

**Comment by adam-mesos** [comment]
(See new issue https://github.com/mesos/chronos/issues/401)
